# Generated by Django 4.1.7 on 2023-03-03 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutstandingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(max_length=255, unique=True)),
                ("token", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Outstanding token",
                "verbose_name_plural": "Outstanding tokens",
            },
        ),
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_token",
                        to="nest.outstandingtoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blacklisted token",
                "verbose_name_plural": "Blacklisted tokens",
            },
        ),
    ]
