# Generated by Django 4.1.7 on 2023-03-25 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                (
                    "avatar_color",
                    models.CharField(
                        choices=[
                            ("#F87171", "Red"),
                            ("#FBBF24", "Yellow"),
                            ("#34D399", "Green"),
                            ("#60A5FA", "Blue"),
                            ("#A78BFA", "Purple"),
                            ("#F472B6", "Pink"),
                        ],
                        max_length=8,
                    ),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=10)),
                ("zip_place", models.CharField(max_length=50)),
                ("num_residents", models.BigIntegerField()),
                ("num_weeks_recipe_rotation", models.BigIntegerField(default=2)),
                ("weekly_budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "home",
                "verbose_name_plural": "homes",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="nest.home",
            ),
        ),
    ]
