# Generated by Django 4.1.7 on 2023-04-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0002_home_user_home_user_homes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("name", models.CharField(max_length=30)),
                ("name_pluralized", models.CharField(max_length=30, null=True)),
                ("abbreviation", models.CharField(max_length=30)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("pieces", "Pieces"),
                            ("weight", "Weight"),
                            ("volume", "Volume"),
                            ("length", "Length"),
                            ("usage", "Usage"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "base_factor",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("is_base_unit", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "unit",
                "verbose_name_plural": "units",
            },
        ),
    ]
