# Generated by Django 4.1.7 on 2023-03-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0002_home_user_homes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="nest.home",
            ),
        ),
    ]
