# Generated by Django 4.1.7 on 2023-04-11 15:18

from django.db import migrations


def add_base_units(apps, schema_editor) -> None:
    Unit = apps.get_model("nest", "Unit")
    units = [
        # Pieces
        Unit(
            name="Stykk",
            name_pluralized="Stykker",
            abbreviation="stk",
            unit_type="pieces",
            base_factor="1.00",
            is_base_unit=True,
            is_default=True,
        ),
        Unit(
            name="Pakke",
            name_pluralized="Pakker",
            abbreviation="pk",
            unit_type="pieces",
            base_factor="1.00",
            is_base_unit=False,
        ),
        Unit(
            name="Fedd",
            abbreviation="fedd",
            unit_type="pieces",
            base_factor="0.10",
            is_base_unit=False,
        ),
        Unit(
            name="Tablett",
            name_pluralized="Tabletter",
            abbreviation="tablett",
            unit_type="pieces",
            base_factor="1.00",
            is_base_unit=False,
        ),
        Unit(
            name="Par",
            abbreviation="par",
            unit_type="pieces",
            base_factor="1.00",
            is_base_unit=False,
        ),
        Unit(
            name="Porsjon",
            abbreviation="prosjon",
            unit_type="pieces",
            base_factor="1.00",
            is_base_unit=False,
        ),
        Unit(
            name="Stilk",
            name_pluralized="Stilker",
            abbreviation="stilk",
            unit_type="pieces",
            base_factor="0.10",
            is_base_unit=False,
        ),
        # Weight
        Unit(
            name="Gram",
            abbreviation="g",
            unit_type="weight",
            base_factor="1.00",
            is_base_unit=True,
        ),
        Unit(
            name="Kilogram",
            abbreviation="kg",
            unit_type="weight",
            base_factor="1000.00",
            is_base_unit=False,
        ),
        Unit(
            name="Teskje",
            name_pluralized="Teskjeer",
            abbreviation="ts",
            unit_type="weight",
            base_factor="5.00",
            is_base_unit=False,
        ),
        Unit(
            name="Spiseskje",
            name_pluralized="Spiseskjeer",
            abbreviation="ss",
            unit_type="weight",
            base_factor="15.00",
            is_base_unit=False,
        ),
        Unit(
            name="Klype",
            name_pluralized="Klyper",
            abbreviation="klype",
            unit_type="weight",
            base_factor="5.00",
            is_base_unit=False,
        ),
        Unit(
            name="Håndfull",
            name_pluralized="Håndfuller",
            abbreviation="håndfull",
            unit_type="weight",
            base_factor="30.00",
            is_base_unit=False,
        ),
        Unit(
            name="Skive",
            name_pluralized="Skiver",
            abbreviation="skive",
            unit_type="weight",
            base_factor="50.00",
            is_base_unit=False,
        ),
        # Volume
        Unit(
            name="Liter",
            abbreviation="l",
            unit_type="volume",
            base_factor="1000.00",
            is_base_unit=False,
        ),
        Unit(
            name="Desiliter",
            abbreviation="dl",
            unit_type="volume",
            base_factor="100.00",
            is_base_unit=False,
        ),
        Unit(
            name="Centiliter",
            abbreviation="cl",
            unit_type="volume",
            base_factor="10.00",
            is_base_unit=False,
        ),
        # Length
        Unit(
            name="Millimeter",
            abbreviation="mm",
            unit_type="length",
            base_factor="1.00",
            is_base_unit=True,
        ),
        Unit(
            name="Centimeter",
            abbreviation="cm",
            unit_type="length",
            base_factor="10.00",
            is_base_unit=False,
        ),
        Unit(
            name="Desimeter",
            abbreviation="dm",
            unit_type="length",
            base_factor="100.00",
            is_base_unit=False,
        ),
        Unit(
            name="Meter",
            abbreviation="m",
            unit_type="length",
            base_factor="1000.00",
            is_base_unit=False,
        ),
        Unit(
            name="100 meter",
            abbreviation="100 m",
            unit_type="length",
            base_factor="100000.00",
            is_base_unit=False,
        ),
        # Usage
        Unit(
            name="Bruk",
            abbreviation="bruk",
            unit_type="usage",
            base_factor="1.00",
            is_base_unit=True,
        ),
        Unit(
            name="Vask",
            abbreviation="vask",
            unit_type="usage",
            base_factor="1.00",
            is_base_unit=False,
        ),
        Unit(
            name="Behandling",
            name_pluralized="Behandlinger",
            abbreviation="behandling",
            unit_type="usage",
            base_factor="1.00",
            is_base_unit=False,
        ),
    ]

    Unit.objects.bulk_create(units)


class Migration(migrations.Migration):

    atomic = True

    dependencies = [
        ("nest", "0003_unit"),
    ]

    operations = [migrations.RunPython(add_base_units, migrations.RunPython.noop)]
