# Generated by Django 4.1.7 on 2023-03-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nest", "0003_user_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="homes",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="nest.home"
            ),
        ),
    ]
