# Generated by Django 4.2.7 on 2024-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_ingredients', '0003_remove_recipeingredientitem_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='is_base_ingredient',
            field=models.BooleanField(default=False, help_text='The ingredient is considered as a base ingredient (something you should already have available).'),
        ),
    ]
