version: "3"

volumes:
  postgres:


services:
  postgres:
    container_name: Postgres
    image: postgres:14.3
    environment:
      - POSTGRES_USER=nest
      - POSTGRES_PASSWORD=nest
      - POSTGRES_DB=nest
    command:
      # We do not need replication-level logging on dev setups
      - --wal_level=minimal
      - --max_wal_senders=0
      #  Double the default value to help index builds
      - --maintenance_work_mem=131072
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"