version: "3"

volumes:
  postgres:
  minio_data:
    driver: local


services:
  postgres:
    container_name: nest-db
    image: postgres:14.3
    environment:
      - POSTGRES_USER=nest
      - POSTGRES_PASSWORD=nest
      - POSTGRES_DB=nest
    command:
      # We do not need replication-level logging on dev setups
      - --wal_level=minimal
      - --max_wal_senders=0
      #  Double the default value to help index builds
      - --maintenance_work_mem=131072
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  minio:
    container_name: nest-minio
    image: bitnami/minio:latest
    restart: unless-stopped
    tty: true
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - MINIO_DEFAULT_BUCKETS=${AWS_S3_BUCKET_NAME}:download
      - MINIO_BROWSER=on
      - CONSOLE_SECURE_TLS_REDIRECT=off
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'