[tool.poetry]
name = "nest"
version = "0.1.0"
description = "Nest is a project for managing my home (nest)"
authors = ["Daniel Kjellid <daniel.kjellid@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10.5"
fastapi = "^0.89.1"
uvicorn = "^0.20.0"
black = "^22.12.0"
isort = "^5.11.4"
python-dotenv = "^0.21.0"
sqlalchemy = "^1.4.46"
alembic = "^1.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
