databases:
  - name: nest-db-prod
    region: frankfurt
    plan: free # starter 7usd/month
    databaseName: nest
    user: nest
    postgresMajorVersion: 14

services:
  - type: web
    region: frankfurt
    plan: free # starter 7usd/month
    name: nest-web-prod
    env: docker
    dockerCommand: ./docker-entrypoint.sh start
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nest-db-prod
          property: connectionString
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: production
      - key: WEB_CONCURRENCY
        value: 4
      - key: SERVE_STATICFILES
        value: true

