# Generated by Django 4.1.7 on 2023-08-15 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("units", "0002_auto_20230413_1530"),
        ("products", "0003_product_allergens_product_carbohydrates_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("default_num_portions", models.PositiveIntegerField(default=4)),
                (
                    "search_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Separate with spaces. Title is included by default.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recipe identifier on a provider's site",
                        null=True,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct link to the recipe on a provider's site",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "Draft"), (2, "Published")], default=1
                    ),
                ),
                (
                    "difficulty",
                    models.SmallIntegerField(
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")], default=1
                    ),
                ),
                (
                    "is_partial_recipe",
                    models.BooleanField(
                        default=False,
                        help_text="Designates if the recipe can be considered a full meal",
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_pescatarian", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingredient",
                "verbose_name_plural": "ingredients",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredientItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("additional_info", models.CharField(max_length=255)),
                (
                    "portion_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_items",
                        to="recipes.recipeingredient",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingredient item",
                "verbose_name_plural": "ingredient items",
            },
        ),
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("number", models.PositiveIntegerField()),
                ("duration", models.DurationField()),
                ("instruction", models.TextField()),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[(1, "Cooking Step"), (2, "Preparation")]
                    ),
                ),
                (
                    "ingredient_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_items",
                        to="recipes.recipeingredientitem",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "step",
                "verbose_name_plural": "steps",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredientItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("title", models.CharField(max_length=255)),
                ("ordering", models.PositiveIntegerField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_groups",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingredient group",
                "verbose_name_plural": "ingredient groups",
            },
            bases=(models.Model, django.db.models.fields.mixins.FieldCacheMixin),
        ),
        migrations.AddField(
            model_name="recipeingredientitem",
            name="ingredient_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_items",
                to="recipes.recipeingredientitemgroup",
            ),
        ),
        migrations.AddField(
            model_name="recipeingredientitem",
            name="portion_quantity_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="units.unit",
            ),
        ),
    ]
