# Generated by Django 4.1.7 on 2023-08-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipestepitem",
            name="ingredient_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_items",
                to="recipes.recipeingredientitem",
            ),
        ),
        migrations.AddField(
            model_name="recipestepitem",
            name="ingredient_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="search_keywords",
            field=models.CharField(
                blank=True,
                help_text="Separate with spaces. Title is included by default.",
                max_length=255,
                null=True,
            ),
        ),
    ]
