# Generated by Django 4.1.7 on 2023-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.SmallIntegerField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="status",
            field=models.SmallIntegerField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
            ),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="step_type",
            field=models.PositiveIntegerField(
                choices=[("cooking", "Cooking Step"), ("preparation", "Preparation")]
            ),
        ),
    ]
