# Generated by Django 4.1.7 on 2023-08-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_remove_recipestep_ingredient_item_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipestep",
            old_name="type",
            new_name="recipe_type",
        ),
        migrations.AlterField(
            model_name="recipeingredientitem",
            name="additional_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
