# Generated by Django 4.1.7 on 2023-08-16 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_rename_type_recipestep_recipe_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipestep",
            old_name="recipe_type",
            new_name="step_type",
        ),
    ]
