# Generated by Django 4.1.7 on 2023-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_rename_recipe_type_recipestep_step_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Recipe identifier on a provider's site",
                max_length=50,
                null=True,
            ),
        ),
    ]
