# Generated by Django 4.1.7 on 2023-08-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_allergens_product_carbohydrates_and_more"),
        ("ingredients", "0002_alter_ingredient_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
