from typing import Any


def get_oda_product_response_dict(*, id: int) -> dict[str, Any]:
    return {
        "id": id,
        "full_name": "M\u00f8llerens Hvetemel Siktet",
        "brand": "M\u00f8llerens",
        "brand_id": 64,
        "name": "Hvetemel",
        "name_extra": "Siktet, 2 kg",
        "front_url": "https://oda.com/no/products/1768-mollerens-hvetemel-siktet/",
        "absolute_url": "/no/products/1768-mollerens-hvetemel-siktet/",
        "gross_price": "26.90",
        "gross_unit_price": "13.45",
        "unit_price_quantity_abbreviation": "kg",
        "unit_price_quantity_name": "kilogram",
        "client_classifiers": [
            {
                "name": "Vegansk",
                "image_url": "https://oda.com/static/products/img/classifier_icons/vegan.c0a8bf457926.png",
                "is_important": False,
                "description": "Produktet er vegansk",
            }
        ],
        "currency": "NOK",
        "discount": None,
        "promotion": None,
        "promotions": [],
        "availability": {
            "is_available": True,
            "description": "",
            "description_short": "",
            "code": "available",
        },
        "metadata": {},
        "images": [
            {
                "large": {
                    "url": "https://bilder.kolonial.no/local_products/d6657665-4d04-42c2-b12f-afe6902c4b12.jpeg?auto=format&fit=max&w=230&s=5ae7d40e60d79ad593559c6f0037ee63",
                    "width": 230,
                    "height": 376,
                },
                "thumbnail": {
                    "url": "https://bilder.kolonial.no/local_products/d6657665-4d04-42c2-b12f-afe6902c4b12.jpeg?auto=format&fit=max&w=184&s=6017145095efa7f062c7879d5f6d3893",
                    "width": 230,
                    "height": 376,
                },
            }
        ],
        "categories": [
            {
                "id": 1215,
                "name": "Fint mel",
                "parent": 1214,
                "parents": [
                    {
                        "id": 15,
                        "name": "Bakeingredienser",
                        "uri": "https://oda.com/no/categories/15-bakeingredienser/",
                        "slug": "bakeingredienser",
                        "parent": None,
                    },
                    {
                        "id": 1214,
                        "name": "Mel",
                        "uri": "https://oda.com/no/categories/15-bakeingredienser/1214-mel/",
                        "slug": "mel",
                        "parent": 15,
                    },
                    {
                        "id": 1215,
                        "name": "Fint mel",
                        "uri": "https://oda.com/no/categories/15-bakeingredienser/1214-mel/1215-fint-mel/",
                        "slug": "fint-mel",
                        "parent": 1214,
                    },
                ],
                "ordering": 9011,
                "description": "",
                "is_new": False,
                "children": [],
                "campaign_banners": [],
                "siblings": [
                    {
                        "id": 1215,
                        "name": "Fint mel",
                        "uri": "https://oda.com/no/categories/15-bakeingredienser/1214-mel/1215-fint-mel/",
                        "slug": "fint-mel",
                        "parent": 1214,
                    },
                    {
                        "id": 1216,
                        "name": "Grovt mel",
                        "uri": "https://oda.com/no/categories/15-bakeingredienser/1214-mel/1216-grovt-mel/",
                        "slug": "grovt-mel",
                        "parent": 1214,
                    },
                    {
                        "id": 1217,
                        "name": "Pizzamel",
                        "uri": "https://oda.com/no/categories/15-bakeingredienser/1214-mel/1217-pizzamel/",
                        "slug": "pizzamel",
                        "parent": 1214,
                    },
                    {
                        "id": 1218,
                        "name": "Matlagningsmel",
                        "uri": "https://oda.com/no/categories/15-bakeingredienser/1214-mel/1218-matlagningsmel/",
                        "slug": "matlagningsmel",
                        "parent": 1214,
                    },
                ],
            }
        ],
        "contents_html": '<div class="contents">\n\n<h3>\nBeskrivelse fra leverand\u00f8ren\n</h3>\n<p>\nSiktet hvetemel er v\u00e5rt mest anvendte bakemel.\n</p>\n\n<h3>\nUtleveringsdager\n</h3>\n\n<p>\nAlle dager\n</p>\n\n<h3>\nSt\u00f8rrelse\n</h3>\n\n<p>\n2 kilogram\n</p>\n\n<h3>\nIngredienser\n</h3>\n\n<p>\nSiktet mel av <strong>HVETE</strong>, melbehandlingsmiddel (ascorbinsyre)\n</p>\n\n<h3>\nLeverand\u00f8r\n</h3>\n\n<p>\nNORGESM\u00d8LLENE AS\n</p>\n\n<p class="disclaimer">\n\nNorgesm\u00f8llene AS\n\nhar levert informasjonen ovenfor.\n\n</p>\n\n</div>\n',
        "nutrition_html": '<table class="nutrition"> <caption>N\u00e6ringsinnhold pr. 100g/ml </caption><tbody> <tr><th> Energi</th> <td>1433 kJ<br> 338 kcal </td></tr> <tr><th> Fett</th> <td>1,60 g </td></tr> <tr class="muted"> <td>hvorav mettede fettsyrer </td><td> 0,40 g </td></tr> <tr class="muted"> <td>hvorav enumettede fettsyrer </td><td> 0,20 g </td></tr> <tr class="muted"> <td>hvorav flerumettede fettsyrer </td><td> 1 g </td></tr> <tr><th> Karbohydrater</th> <td>67,90 g </td></tr> <tr class="muted"> <td>hvorav sukkerarter </td><td> 2,70 g </td></tr> <tr><th> Kostfiber</th> <td>3,60 g </td></tr> <tr><th> Protein</th> <td>11,20 g </td></tr> <tr><th> Salt</th> <td>0 g </td></tr> </tbody></table>\n',
        "bottle_deposit": None,
        "alternative_products": [
            {
                "id": 35,
                "full_name": "M\u00f8llerens Hvetemel Siktet",
                "brand": "M\u00f8llerens",
                "brand_id": 64,
                "name": "Hvetemel",
                "name_extra": "Siktet, 1 kg",
                "front_url": "https://oda.com/no/products/35-mollerens-hvetemel-siktet/",
                "absolute_url": "/no/products/35-mollerens-hvetemel-siktet/",
                "gross_price": "14.90",
                "gross_unit_price": "14.90",
                "unit_price_quantity_abbreviation": "kg",
                "unit_price_quantity_name": "kilogram",
                "client_classifiers": [
                    {
                        "name": "Vegansk",
                        "image_url": "https://oda.com/static/products/img/classifier_icons/vegan.c0a8bf457926.png",
                        "is_important": False,
                        "description": "Produktet er vegansk",
                    }
                ],
                "currency": "NOK",
                "discount": None,
                "promotion": None,
                "promotions": [],
                "availability": {
                    "is_available": True,
                    "description": "",
                    "description_short": "",
                    "code": "available",
                },
                "metadata": {},
                "images": [
                    {
                        "large": {
                            "url": "https://bilder.kolonial.no/local_products/d31e8093-f883-4d1f-834b-558d6a0b47cf.jpeg?auto=format&fit=max&w=272&s=3090db68f54f245eb601e24d39ccd0fc",
                            "width": 272,
                            "height": 376,
                        },
                        "thumbnail": {
                            "url": "https://bilder.kolonial.no/local_products/d31e8093-f883-4d1f-834b-558d6a0b47cf.jpeg?auto=format&fit=max&w=217&s=3a25019ccc2a0e40242f91c29bed44f0",
                            "width": 272,
                            "height": 376,
                        },
                    }
                ],
            },
            {
                "id": 28192,
                "full_name": "Kolonihagen Hvetemel Siktet \u00d8kologisk",
                "brand": "Kolonihagen",
                "brand_id": 1242,
                "name": "Hvetemel Siktet",
                "name_extra": "\u00d8kologisk, 1 kg",
                "front_url": "https://oda.com/no/products/28192-kolonihagen-hvetemel-siktet-okologisk/",
                "absolute_url": "/no/products/28192-kolonihagen-hvetemel-siktet-okologisk/",
                "gross_price": "24.20",
                "gross_unit_price": "24.20",
                "unit_price_quantity_abbreviation": "kg",
                "unit_price_quantity_name": "kilogram",
                "client_classifiers": [
                    {
                        "name": "\u00d8kologisk",
                        "image_url": "https://oda.com/static/products/img/classifier_icons/organic.8cd2f16bb368.png",
                        "is_important": False,
                        "description": "Produktet er \u00f8kologisk",
                    },
                    {
                        "name": "Debio",
                        "image_url": "https://bilder.kolonial.no/certifications/7d512a62-5004-4ee3-8342-da9eeceb7460.png?auto=format&fit=max&w=60&s=60163fadf10b3a94bfd6ede80cc3aff3",
                        "is_important": False,
                        "description": "Debio er en ikke-statlig medlemsorganisasjon som kontrollerer og godkjenner \u00f8kologisk produksjon i Norge, og at produkter som markedsf\u00f8res med henvisning til den \u00f8kologiske produksjonsmetoden, tilfredsstiller kravene i regelverket.",
                    },
                ],
                "currency": "NOK",
                "discount": None,
                "promotion": None,
                "promotions": [],
                "availability": {
                    "is_available": True,
                    "description": "",
                    "description_short": "",
                    "code": "available",
                },
                "metadata": {},
                "images": [
                    {
                        "large": {
                            "url": "https://bilder.kolonial.no/produkter/4d7dd7cd-8628-4dee-8f8a-6843f61e8898.jpeg?auto=format&fit=max&w=698&s=f23135dbe75cb8544b11e7c439924e32",
                            "width": 2095,
                            "height": 3000,
                        },
                        "thumbnail": {
                            "url": "https://bilder.kolonial.no/produkter/4d7dd7cd-8628-4dee-8f8a-6843f61e8898.jpeg?auto=format&fit=max&w=210&s=bfc5773e16bdf1b326a347721a49f83a",
                            "width": 2095,
                            "height": 3000,
                        },
                    }
                ],
            },
            {
                "id": 31258,
                "full_name": "Holli M\u00f8lle \u00d8kologisk Siktet Landhvete",
                "brand": "Holli M\u00f8lle",
                "brand_id": 1512,
                "name": "\u00d8kologisk Siktet Landhvete",
                "name_extra": "1 kg",
                "front_url": "https://oda.com/no/products/31258-holli-molle-okologisk-siktet-landhvete/",
                "absolute_url": "/no/products/31258-holli-molle-okologisk-siktet-landhvete/",
                "gross_price": "50.40",
                "gross_unit_price": "50.40",
                "unit_price_quantity_abbreviation": "kg",
                "unit_price_quantity_name": "kilogram",
                "client_classifiers": [
                    {
                        "name": "\u00d8kologisk",
                        "image_url": "https://oda.com/static/products/img/classifier_icons/organic.8cd2f16bb368.png",
                        "is_important": False,
                        "description": "Produktet er \u00f8kologisk",
                    },
                    {
                        "name": "Debio",
                        "image_url": "https://bilder.kolonial.no/certifications/7d512a62-5004-4ee3-8342-da9eeceb7460.png?auto=format&fit=max&w=60&s=60163fadf10b3a94bfd6ede80cc3aff3",
                        "is_important": False,
                        "description": "Debio er en ikke-statlig medlemsorganisasjon som kontrollerer og godkjenner \u00f8kologisk produksjon i Norge, og at produkter som markedsf\u00f8res med henvisning til den \u00f8kologiske produksjonsmetoden, tilfredsstiller kravene i regelverket.",
                    },
                ],
                "currency": "NOK",
                "discount": None,
                "promotion": None,
                "promotions": [],
                "availability": {
                    "is_available": True,
                    "description": "",
                    "description_short": "",
                    "code": "available",
                },
                "metadata": {},
                "images": [
                    {
                        "large": {
                            "url": "https://bilder.kolonial.no/produkter/44fe4639-7484-4996-a8fc-16d7af101139.jpg?auto=format&fit=max&w=633&s=157757df99a9c561e1032ad243bd2fa1",
                            "width": 1898,
                            "height": 3000,
                        },
                        "thumbnail": {
                            "url": "https://bilder.kolonial.no/produkter/44fe4639-7484-4996-a8fc-16d7af101139.jpg?auto=format&fit=max&w=190&s=723576fc05a1bdd78a9cd4a47e8a2897",
                            "width": 1898,
                            "height": 3000,
                        },
                    }
                ],
            },
        ],
        "discount_mix_and_match_products": None,
        "detailed_info": {
            "country": "NO",
            "local": [
                {
                    "language": "nb",
                    "language_name": "Norsk (bokm\u00e5l)",
                    "local_product_name": "Hvetemel",
                    "short_description": "",
                    "description_from_supplier": "Siktet hvetemel er v\u00e5rt mest anvendte bakemel.",
                    "nutrition_info_table": {
                        "title": "N\u00e6ringsinnhold pr. 100g/ml",
                        "rows": [
                            {
                                "key": "Energi",
                                "value": "1433 kJ / 338 kcal",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "Fett",
                                "value": "1.60 g",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "hvorav mettede fettsyrer",
                                "value": "0.40 g",
                                "badge": None,
                                "indent": 1,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "hvorav enumettede fettsyrer",
                                "value": "0.20 g",
                                "badge": None,
                                "indent": 1,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "hvorav flerumettede fettsyrer",
                                "value": "1 g",
                                "badge": None,
                                "indent": 1,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "Karbohydrater",
                                "value": "67.90 g",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "hvorav sukkerarter",
                                "value": "2.70 g",
                                "badge": None,
                                "indent": 1,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "Kostfiber",
                                "value": "3.60 g",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "Protein",
                                "value": "11.20 g",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "Salt",
                                "value": "0 g",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                        ],
                        "disclaimers": None,
                    },
                    "contents_table": {
                        "title": None,
                        "rows": [
                            {
                                "key": "Beskrivelse fra leverand\u00f8ren",
                                "value": "Siktet hvetemel er v\u00e5rt mest anvendte bakemel.",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": "description-from-supplier",
                            },
                            {
                                "key": "Utleveringsdager",
                                "value": "alle dager",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "Opprinnelsesland",
                                "value": "Norge",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "St\u00f8rrelse",
                                "value": "2 kilogram",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                            {
                                "key": "Ingredienser",
                                "value": "Siktet mel av HVETE, melbehandlingsmiddel (ascorbinsyre)",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": {
                                    "keywords": ["hvete"],
                                    "emphasis_type": "bold",
                                    "reason": "allergens",
                                },
                                "key_id": None,
                            },
                            {
                                "key": "Leverand\u00f8r",
                                "value": "Norgesm\u00f8llene AS",
                                "badge": None,
                                "indent": None,
                                "tooltip": None,
                                "link": None,
                                "emphasis": None,
                                "key_id": None,
                            },
                        ],
                        "disclaimers": [
                            "Norgesm\u00f8llene AS har levert informasjonen ovenfor."
                        ],
                    },
                    "hazards": None,
                }
            ],
        },
        "is_product_included_in_product_lists": None,
        "is_restricted": False,
    }
