# Generated by Django 4.1.7 on 2023-10-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("default_num_portions", models.PositiveIntegerField(default=4)),
                (
                    "search_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Separate with spaces. Title is included by default.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Recipe identifier on a providers site",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct link to the recipe on a providers site",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("hidden", "Hidden"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=20,
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_pescatarian", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
            },
        ),
    ]
