"""Add user model

Revision ID: d9d40ffabdd9
Revises: 25c72fefa8e4
Create Date: 2023-01-30 16:13:01.090967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d9d40ffabdd9"
down_revision = "25c72fefa8e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_schema_email", table_name="user_schema")
    op.drop_index("ix_user_schema_id", table_name="user_schema")
    op.drop_table("user_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_schema",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "first_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "password", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="user_schema_pkey"),
    )
    op.create_index("ix_user_schema_id", "user_schema", ["id"], unique=False)
    op.create_index(
        "ix_user_schema_email", "user_schema", ["email"], unique=False
    )
    # ### end Alembic commands ###
