"""Add user model

Revision ID: 25c72fefa8e4
Revises: 
Create Date: 2023-01-28 16:53:12.001558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25c72fefa8e4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_schema",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_schema_email"), "user_schema", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_user_schema_id"), "user_schema", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_schema_id"), table_name="user_schema")
    op.drop_index(op.f("ix_user_schema_email"), table_name="user_schema")
    op.drop_table("user_schema")
    # ### end Alembic commands ###
