# Generated by Django 4.1.7 on 2023-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=10)),
                ("zip_place", models.CharField(max_length=50)),
                ("num_residents", models.BigIntegerField()),
                ("num_weeks_recipe_rotation", models.BigIntegerField(default=2)),
                ("weekly_budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "home",
                "verbose_name_plural": "homes",
            },
        ),
    ]
