# Generated by Django 4.1.7 on 2023-05-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
