# Generated by Django 4.1.7 on 2023-05-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0003_product_carbohydrates_product_carbohydrates_polyols_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allergens",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(null=True),
        ),
    ]
