# Generated by Django 4.1.7 on 2023-05-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_allergens_product_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="contains_gluten",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="contains_lactose",
            field=models.BooleanField(default=False),
        ),
    ]
