"""Add initial user and auth models

Revision ID: 2c99ba3af43e
Revises: 
Create Date: 2023-02-01 11:28:08.064559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c99ba3af43e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_user_email"), "users_user", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_users_user_id"), "users_user", ["id"], unique=True
    )
    op.create_table(
        "tokens_outstanding_token",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("jti", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users_user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.create_index(
        op.f("ix_tokens_outstanding_token_id"),
        "tokens_outstanding_token",
        ["id"],
        unique=True,
    )
    op.create_table(
        "tokens_blacklisted_token",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("blacklisted_at", sa.DateTime(), nullable=True),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["token_id"], ["tokens_outstanding_token.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tokens_blacklisted_token_id"),
        "tokens_blacklisted_token",
        ["id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tokens_blacklisted_token_id"),
        table_name="tokens_blacklisted_token",
    )
    op.drop_table("tokens_blacklisted_token")
    op.drop_index(
        op.f("ix_tokens_outstanding_token_id"),
        table_name="tokens_outstanding_token",
    )
    op.drop_table("tokens_outstanding_token")
    op.drop_index(op.f("ix_users_user_id"), table_name="users_user")
    op.drop_index(op.f("ix_users_user_email"), table_name="users_user")
    op.drop_table("users_user")
    # ### end Alembic commands ###
