# Generated by Django 4.2.7 on 2023-11-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_allergens_product_carbohydrates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbohydrates_polyols',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbohydrates_starch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbohydrates_sugars',
        ),
        migrations.RemoveField(
            model_name='product',
            name='energy_kcal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='energy_kj',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fat_monounsaturated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fat_polyunsaturated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fat_saturated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fibres',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sodium',
        ),
    ]
