# Generated by Django 4.2.7 on 2023-11-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_remove_product_carbohydrates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('energy_kj', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energy_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_saturated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_monounsaturated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat_polyunsaturated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrates_sugars', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrates_polyols', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrates_starch', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fibres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='protein')),
                ('salt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='salt')),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sodium')),
                ('products', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='products.product')),
            ],
            options={
                'verbose_name': 'product nutrition',
                'verbose_name_plural': 'product nutrition',
            },
        ),
    ]
