name: Dependabot automerge

on: pull_request

jobs:
  automerge:
    uses: danielkjellid/github-actions/.github/workflows/python.yaml@dependabot-automerge-action
    permissions:
      contents: write
      pull-requests: write
    with:
      check-regexp: '(CI done|tests)'

