name: Dependabot automerge

on: pull_request

jobs:
  automerge:
    name: 'Automerge'
    uses: danielkjellid/github-actions/.github/workflows/dependabot-automerge.yaml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      name: 'Automerge'
      check-regexp: '(CI done|tests)'