# Generated by Django 4.1.7 on 2023-10-30 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified time"),
                ),
                ("number", models.PositiveIntegerField()),
                ("duration", models.DurationField()),
                ("instruction", models.TextField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("cooking", "Cooking Step"),
                            ("preparation", "Preparation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "step",
                "verbose_name_plural": "steps",
            },
        ),
    ]
